#pragma once

#define WC_LAB2 "cgLab2Window"
#define WC_LAB2_NOTIFY "cgLab2NotifyWindow"
#define WC_LAB2_SCENE "cgLab2SceneWindow"
#define WC_LAB2_CONTROLPANEL "cgLab2ControlPanel"

#define MARGIN_PX 2
#define CONTROL_PANEL_WIDTH 300

/* MENU ID's */
#define IDM_OPEN 10


/* CONTROL PANEL ID's */
enum CONTROL_IDS {
	IDC_WIREFRAME = 100,
	IDC_SHADE_MODEL_FLAT,
	IDC_SHADE_MODEL_SMOOTH,
	IDC_HIERARCHY_TREE,
	IDC_APRONMOVE_TRACK,
	IDC_SUPPORTMOVE_TRACK,
	IDC_SUPPORT_HEAD_MOVE_TRACK,
	IDC_SUPPORT_OFFSET_TRACK,
	IDC_SUPPORT_HEAD_BOLTS,
	IDC_SCREW_DRIVE,
	IDC_TAILSTOCKMOVE_TRACK,
	IDC_SPINDLEROTATION_TRACK,
	IDC_SPINDLEJAWSMOVE_TRACK,
};